# -*- coding: utf-8 -*-
"""Copy of Week2_sales_data_analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pUEiILm1emZXbGXlUOBJDE-Mp_31PB29
"""

import pandas as pd
import matplotlib.pyplot as plt

df = pd.read_csv('week2_sales_analysis_output.csv')
df.head()

df.info()

total_sales = df['total_amount'].sum()
print("Total Sales Amount:", total_sales)

best_product = df.groupby('product_name')['total_amount'].sum().idxmax()
print("Best Selling Product:", best_product)

df['order_date'] = pd.to_datetime(df['order_date'])
df['month'] = df['order_date'].dt.month

monthly_sales = df.groupby('month')['total_amount'].sum()
monthly_sales

monthly_sales.plot()
plt.xlabel("Month")
plt.ylabel("Total Sales Amount")
plt.title("Monthly Sales Analysis")
plt.show()